### ISSUE TITLE
关于固件

### ISSUE THREAD

**Issue by LanDaZhuang** [Tnze/miband-heart-rate#2]
想问下你的小米手环6固件版本是多少呀？我打开了心率广播后发现数据并不正确

**Comment by Tnze** [comment]
不正确是怎么不正确？应该和固件版本没关系，数据格式不会改的

**Comment by LanDaZhuang** [comment]
找到问题了，我没开启运动模式，收到的数据是0xff。。。
（先看到Github的内容，然后逛了会B站找到大大您的文章了hhhhh)
