### ISSUE TITLE
如何过滤设备

### ISSUE THREAD

**Issue by cary-hu** [Tnze/miband-heart-rate#3]
在办公室启用接收广播，会收集到多个设备的广播，如何区分哪个是自己的设备呢？
![image](https://github.com/user-attachments/assets/f5dacd2b-21cd-47a8-a898-100d0a368a6d)

**Comment by Tnze** [comment]
改代码，有设备地址

**Comment by cary-hu** [comment]
Ok, 看到B站上的讨论了，感谢回复。
